# Generated by Django 4.1.7 on 2023-03-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0002_alter_visitor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(default='Tanbir', max_length=50),
        ),
    ]
